return None if not installed
SergeyPirogov/webdriver_manager pull request #336
Opened 2022-03-04 04:13 UTC by luizoti

This is a simple modification.

1. supress_errors hide powershell error messages and etc.
2. If the browser is not installed, return None (message is still UNKNOW)
3. Asks if the browser is installed.

2022-03-04 04:13 UTC, pep8speaks commented
Hello @luizoti! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`webdriver_manager/utils.py`](https://github.com/SergeyPirogov/webdriver_manager/blob/a1b1b141c8d58da1c8938fbb21180fb7e8b23e1c/webdriver_manager/utils.py):

> [Line 245:80](https://github.com/SergeyPirogov/webdriver_manager/blob/a1b1b141c8d58da1c8938fbb21180fb7e8b23e1c/webdriver_manager/utils.py#L245): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 249:80](https://github.com/SergeyPirogov/webdriver_manager/blob/a1b1b141c8d58da1c8938fbb21180fb7e8b23e1c/webdriver_manager/utils.py#L249): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 79 characters)

2022-03-05 05:00 UTC, aleksandr-kotlyar commented
@luizoti what if just make disable WDM logs?

2022-03-05 13:35 UTC, luizoti commented
> what if just make disable WDM logs? Would it be better than making this overhead on webdriver-manager

From my point of view, if there is an option that turns off error messages and another that turns off information messages, there is no problem, I include this optional argument exactly because I didn't see any sense in the error message, since just printing the message didn't make it clear what happened (so I added a question too).

2022-03-05 15:02 UTC, aleksandr-kotlyar commented
@luizoti thank you! You made me think to remove this error message at all. Who wants - can go to sources and debug.
Because the implementation of disabling this error message is a huge overhead.

2022-03-05 15:04 UTC, aleksandr-kotlyar commented
@luizoti You can make a PR with removing `"with the command {cmd}"` from this logging message
```python
        log(f'Could not get version for {browser_type} with the command: {cmd}')
```

2022-03-07 03:46 UTC, luizoti commented
I updated, removed the cmd and asked the question whether the browser is installed or not in place.

2022-03-08 20:27 UTC, aleksandr-kotlyar requested changes

2022-03-08 20:27 UTC, aleksandr-kotlyar commented on webdriver_manager/utils.py
> +    current_version = version.group(0) if version else None
leave this part like it was before please

2022-03-08 20:27 UTC, aleksandr-kotlyar commented on webdriver_manager/utils.py
> +        }""")
leave this part like it was before please (2)

2022-03-08 20:27 UTC, aleksandr-kotlyar commented on webdriver_manager/utils.py
> +        }""")
leave this part like it was before please (2)

2022-03-08 20:27 UTC, aleksandr-kotlyar commented on webdriver_manager/utils.py
> +        log(f'Could not get version for {browser_type}, is {browser_type} installed?')
Only this change means.

2022-03-08 20:27 UTC, aleksandr-kotlyar commented on webdriver_manager/utils.py
> +        log(f'Could not get version for {browser_type}, is {browser_type} installed?')
Only this change means.

2022-03-08 20:29 UTC, aleksandr-kotlyar requested changes

2022-03-08 20:29 UTC, aleksandr-kotlyar commented on webdriver_manager/utils.py
> +    current_version = version.group(0) if version else None
leave this part like it was before please

2022-03-10 07:17 UTC, closed without merging